// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReissueTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdempotentKey string                 `protobuf:"bytes,1,opt,name=idempotentKey,proto3" json:"idempotentKey,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReissueTokenRequest) Reset() {
	*x = ReissueTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReissueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReissueTokenRequest) ProtoMessage() {}

func (x *ReissueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReissueTokenRequest.ProtoReflect.Descriptor instead.
func (*ReissueTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ReissueTokenRequest) GetIdempotentKey() string {
	if x != nil {
		return x.IdempotentKey
	}
	return ""
}

func (x *ReissueTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// RFC 6819  Refresh Token Rotation
type JwtTokenResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccessToken           string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken          string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	AccessTokenExpiresIn  int64                  `protobuf:"varint,3,opt,name=accessTokenExpiresIn,proto3" json:"accessTokenExpiresIn,omitempty"`
	RefreshTokenExpiresIn int64                  `protobuf:"varint,4,opt,name=refreshTokenExpiresIn,proto3" json:"refreshTokenExpiresIn,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JwtTokenResponse) Reset() {
	*x = JwtTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JwtTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtTokenResponse) ProtoMessage() {}

func (x *JwtTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtTokenResponse.ProtoReflect.Descriptor instead.
func (*JwtTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *JwtTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *JwtTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *JwtTokenResponse) GetAccessTokenExpiresIn() int64 {
	if x != nil {
		return x.AccessTokenExpiresIn
	}
	return 0
}

func (x *JwtTokenResponse) GetRefreshTokenExpiresIn() int64 {
	if x != nil {
		return x.RefreshTokenExpiresIn
	}
	return 0
}

type UserInfoInApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoInApplicationRequest) Reset() {
	*x = UserInfoInApplicationRequest{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoInApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoInApplicationRequest) ProtoMessage() {}

func (x *UserInfoInApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoInApplicationRequest.ProtoReflect.Descriptor instead.
func (*UserInfoInApplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfoInApplicationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserInfoInApplicationRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UserInfoInApplicationPageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 조회된 사용자 정보 목록
	Items []*UserInfoInApplicationResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// 현재 페이지 번호 (1부터 시작)
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// 페이지 크기
	Size       int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	TotalItems int32 `protobuf:"varint,4,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	// 전체 페이지 수
	TotalPages    int32 `protobuf:"varint,5,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoInApplicationPageResponse) Reset() {
	*x = UserInfoInApplicationPageResponse{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoInApplicationPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoInApplicationPageResponse) ProtoMessage() {}

func (x *UserInfoInApplicationPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoInApplicationPageResponse.ProtoReflect.Descriptor instead.
func (*UserInfoInApplicationPageResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfoInApplicationPageResponse) GetItems() []*UserInfoInApplicationResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UserInfoInApplicationPageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *UserInfoInApplicationPageResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UserInfoInApplicationPageResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *UserInfoInApplicationPageResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type UserInfoInApplicationResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName        string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	ApplicationRole string                 `protobuf:"bytes,3,opt,name=applicationRole,proto3" json:"applicationRole,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserInfoInApplicationResponse) Reset() {
	*x = UserInfoInApplicationResponse{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoInApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoInApplicationResponse) ProtoMessage() {}

func (x *UserInfoInApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoInApplicationResponse.ProtoReflect.Descriptor instead.
func (*UserInfoInApplicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoInApplicationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfoInApplicationResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfoInApplicationResponse) GetApplicationRole() string {
	if x != nil {
		return x.ApplicationRole
	}
	return ""
}

func (x *UserInfoInApplicationResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Passport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	ApplicationId string                 `protobuf:"bytes,3,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	UserInfo      *UserInfoResponse      `protobuf:"bytes,4,opt,name=userInfo,proto3,oneof" json:"userInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Passport) Reset() {
	*x = Passport{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Passport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passport) ProtoMessage() {}

func (x *Passport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passport.ProtoReflect.Descriptor instead.
func (*Passport) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *Passport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Passport) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Passport) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Passport) GetUserInfo() *UserInfoResponse {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UserInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Email           *string                `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Name            *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	ApplicationRole string                 `protobuf:"bytes,3,opt,name=applicationRole,proto3" json:"applicationRole,omitempty"`
	AccessLevel     int32                  `protobuf:"varint,4,opt,name=accessLevel,proto3" json:"accessLevel,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoResponse) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserInfoResponse) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserInfoResponse) GetApplicationRole() string {
	if x != nil {
		return x.ApplicationRole
	}
	return ""
}

func (x *UserInfoResponse) GetAccessLevel() int32 {
	if x != nil {
		return x.AccessLevel
	}
	return 0
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x1a\x1bgoogle/protobuf/empty.proto\"_\n" +
	"\x13ReissueTokenRequest\x12$\n" +
	"\ridempotentKey\x18\x01 \x01(\tR\ridempotentKey\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\"\xc2\x01\n" +
	"\x10JwtTokenResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x122\n" +
	"\x14accessTokenExpiresIn\x18\x03 \x01(\x03R\x14accessTokenExpiresIn\x124\n" +
	"\x15refreshTokenExpiresIn\x18\x04 \x01(\x03R\x15refreshTokenExpiresIn\"F\n" +
	"\x1cUserInfoInApplicationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\xc1\x01\n" +
	"!UserInfoInApplicationPageResponse\x124\n" +
	"\x05items\x18\x01 \x03(\v2\x1e.UserInfoInApplicationResponseR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x1e\n" +
	"\n" +
	"totalItems\x18\x04 \x01(\x05R\n" +
	"totalItems\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\x93\x01\n" +
	"\x1dUserInfoInApplicationResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12(\n" +
	"\x0fapplicationRole\x18\x03 \x01(\tR\x0fapplicationRole\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"\x95\x01\n" +
	"\bPassport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12$\n" +
	"\rapplicationId\x18\x03 \x01(\tR\rapplicationId\x122\n" +
	"\buserInfo\x18\x04 \x01(\v2\x11.UserInfoResponseH\x00R\buserInfo\x88\x01\x01B\v\n" +
	"\t_userInfo\"\xa5\x01\n" +
	"\x10UserInfoResponse\x12\x19\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12(\n" +
	"\x0fapplicationRole\x18\x03 \x01(\tR\x0fapplicationRole\x12 \n" +
	"\vaccessLevel\x18\x04 \x01(\x05R\vaccessLevelB\b\n" +
	"\x06_emailB\a\n" +
	"\x05_name2\xec\x01\n" +
	"\x0fUserInfoService\x128\n" +
	"\x13GetPassportByBearer\x12\x16.google.protobuf.Empty\x1a\t.Passport\x12@\n" +
	"\x13GetUserInfoByBearer\x12\x16.google.protobuf.Empty\x1a\x11.UserInfoResponse\x12]\n" +
	"\x18GetUserInfoInApplication\x12\x1d.UserInfoInApplicationRequest\x1a\".UserInfoInApplicationPageResponse2G\n" +
	"\fTokenService\x127\n" +
	"\freissueToken\x12\x14.ReissueTokenRequest\x1a\x11.JwtTokenResponseB\bZ\x06/protob\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_auth_proto_goTypes = []any{
	(*ReissueTokenRequest)(nil),               // 0: ReissueTokenRequest
	(*JwtTokenResponse)(nil),                  // 1: JwtTokenResponse
	(*UserInfoInApplicationRequest)(nil),      // 2: UserInfoInApplicationRequest
	(*UserInfoInApplicationPageResponse)(nil), // 3: UserInfoInApplicationPageResponse
	(*UserInfoInApplicationResponse)(nil),     // 4: UserInfoInApplicationResponse
	(*Passport)(nil),                          // 5: Passport
	(*UserInfoResponse)(nil),                  // 6: UserInfoResponse
	(*emptypb.Empty)(nil),                     // 7: google.protobuf.Empty
}
var file_proto_auth_proto_depIdxs = []int32{
	4, // 0: UserInfoInApplicationPageResponse.items:type_name -> UserInfoInApplicationResponse
	6, // 1: Passport.userInfo:type_name -> UserInfoResponse
	7, // 2: UserInfoService.GetPassportByBearer:input_type -> google.protobuf.Empty
	7, // 3: UserInfoService.GetUserInfoByBearer:input_type -> google.protobuf.Empty
	2, // 4: UserInfoService.GetUserInfoInApplication:input_type -> UserInfoInApplicationRequest
	0, // 5: TokenService.reissueToken:input_type -> ReissueTokenRequest
	5, // 6: UserInfoService.GetPassportByBearer:output_type -> Passport
	6, // 7: UserInfoService.GetUserInfoByBearer:output_type -> UserInfoResponse
	3, // 8: UserInfoService.GetUserInfoInApplication:output_type -> UserInfoInApplicationPageResponse
	1, // 9: TokenService.reissueToken:output_type -> JwtTokenResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	file_proto_auth_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_auth_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
